chg: Adjust CI to be more efficient

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,5 +1,11 @@
 name: ci
-on: [push]
+on:
+  push:
+    branches: [main]
+  pull_request:
+    branches: [main]
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
 jobs:
   build:
     runs-on: ${{ matrix.os }}
@@ -9,6 +15,22 @@ jobs:
     steps:
       - name: Checkout repository and submodules
         uses: actions/checkout@v2
+      - name: Cache Bazel diretories
+        uses: actions/cache@v2
+        env:
+          cache-name: bazel-cache
+        with:
+          path: |
+            ~/.cache/bazelisk
+            ~/.cache/bazel
+          key: ${{ runner.os }}-${{ env.cache-name }}
+      - name: Find untagged tests
+        run: |
+          UNTAGGED_TESTS=$(bazel --bazelrc=.github/github.bazelrc query 'tests(//...) except attr(tags, L0, tests(//...)) except attr(tags, L1, tests(//...)) except attr(tags, L2, tests(//...)) except attr(tags, L3, tests(//...)) except attr(tags, Nightly, tests(//...)) except attr(tags, manual, tests(//...))')
+          if [ -n "${UNTAGGED_TESTS}" ]; then
+            echo "ERROR: Following Bazel tests are untagged: ${UNTAGGED_TESTS}" 1>&2
+            exit 1
+          fi
       - name: Build
         run: bazel --bazelrc=.github/github.bazelrc build //...
       - name: Test
